FROM golang:1.26 AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/api ./cmd/api

FROM gcr.io/distroless/static-debian12

WORKDIR /app

COPY --from=build /out/api /app/api

EXPOSE 8081

ENTRYPOINT ["/app/api"]
